version: "3.2"

services:
  api:
    build: ./images/api
    ports:
      - 3000:3000
    environment:
      NODE_ENV:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test
      POSTGRES_HOST: db
      PORT:
    volumes:
      - ./images/api/src:/usr/app/src
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      POSTGRES_HOST_AUTH_METHOD:
    volumes:
      - ./_volumes/db/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10